In [1]:
import torch
torch.empty(size=(2,3,4))


tensor([[[1.1353e+30, 2.3069e-37, 7.4161e+31, 2.1160e-37],
         [4.5545e+30, 7.4161e+31, 1.1353e+30, 2.3069e-37],
         [2.1159e-37, 9.1526e+02, 1.2147e-38, 1.4621e+04]],

        [[1.2148e-38, 2.3395e+05, 1.2149e-38, 3.7432e+06],
         [1.2149e-38, 5.9892e+07, 1.2150e-38, 2.0780e-10],
         [5.7418e-38, 1.5322e+10, 2.8299e+35, 2.4515e+11]]])

In [2]:
torch.ones(size=(3,4))*2

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [3]:
t=torch.arange(6)
t.dtype


torch.int64

In [4]:
t.double().dtype

torch.float64

In [5]:
torch.linspace(start = 1 , end=20, steps=30).shape
torch.Size([30])
import numpy as np
arr=np.arange(16)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
 t=torch.tensor(arr)
 t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
t=torch.from_numpy(arr)
t.numpy()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [12]:
{"type":"string"}
torch.tensor([1,2,3,4],dtype=torch.float32,device=device,requires_grad=True)

torch.eye(5)


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
torch.diag(torch.tensor([1,2,3,5]))

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 5]])

In [14]:
t= torch.rand(size=(4,4))
t


tensor([[0.4628, 0.5639, 0.8948, 0.9287],
        [0.8918, 0.5897, 0.2449, 0.0469],
        [0.3756, 0.0101, 0.4101, 0.6100],
        [0.1379, 0.4615, 0.5632, 0.6557]])

In [15]:
torch.diag(t)

tensor([0.4628, 0.5897, 0.4101, 0.6557])

In [16]:
t=torch.tensor([1,2,3,4,5,6])
t.shape
torch.Size([6])
t.unsqueeze(axis=1).squeeze()


tensor([1, 2, 3, 4, 5, 6])

In [17]:
t=torch.arange(15)
t


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
t.view(1,3,5)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]])

In [19]:
tensor=torch.linspace(0,10,24).reshape(2,3,4)
tensor


tensor([[[ 0.0000,  0.4348,  0.8696,  1.3043],
         [ 1.7391,  2.1739,  2.6087,  3.0435],
         [ 3.4783,  3.9130,  4.3478,  4.7826]],

        [[ 5.2174,  5.6522,  6.0870,  6.5217],
         [ 6.9565,  7.3913,  7.8261,  8.2609],
         [ 8.6957,  9.1304,  9.5652, 10.0000]]])

In [20]:
tensor[0][:,:2]

tensor([[0.0000, 0.4348],
        [1.7391, 2.1739],
        [3.4783, 3.9130]])

In [21]:
tensor.shape
torch.Size([2, 3, 4])
tensor.sum(axis=2)


tensor([[ 2.6087,  9.5652, 16.5217],
        [23.4783, 30.4348, 37.3913]])

In [22]:
x = torch.ones(size=(3,4))
y = torch.ones(size=(4,5))*3
torch.matmul(x,y)


tensor([[12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12.]])

In [23]:
x = torch.ones(size=(3,4))
y = torch.ones(size=(3,4))*4
print(x)
print(y)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [24]:
z=torch.empty(size=(3,4))
torch.add(x,y,out=z)
z

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [25]:
z=torch.add(x,y)
z


tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [26]:
z=x+y
#x+=y
x.add_(y)
x


tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [27]:
torch.arange(4)*3 <5

tensor([ True,  True, False, False])

In [28]:
x.pow(2)

tensor([[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]])