In [1]:
import numpy as np
class SimpleRNN:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights and biases
        self.W_hx = np.random.randn(hidden_size, input_size)
        self.W_hh = np.random.randn(hidden_size, hidden_size)
        self.W_yh = np.random.randn(output_size, hidden_size)
        self.b_h = np.zeros((hidden_size, 1))
        self.b_y = np.zeros((output_size, 1))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def softmax(self, x):
        exp_x = np.exp(x - np.max(x))  # Avoid overflow
        return exp_x / exp_x.sum(axis=0)

    def forward(self, inputs):
        # Initialize hidden state
        h = np.zeros((self.hidden_size, 1))

        # Lists to store intermediate hidden states and outputs
        h_states = []
        outputs = []

        # Forward pass through time steps
        for x in inputs:
            # Update hidden state
            h = self.sigmoid(np.dot(self.W_hx, x) + np.dot(self.W_hh, h) + self.b_h)
            h_states.append(h)

            # Compute output
            y = self.softmax(np.dot(self.W_yh, h) + self.b_y)
            outputs.append(y)
        return h_states, outputs

# Example usage
if __name__ == "__main__":
    # Define input sequence (3 time steps, 2 features)
    input_sequence = [np.array([[0.2], [0.4]]), np.array([[0.7], [0.9]]), np.array([[0.3], [0.5]])]

    # Create an RNN with 2 hidden units and 2 output units
    rnn = SimpleRNN(input_size=2, hidden_size=2, output_size=2)

    # Perform forward pass
    hidden_states, outputs = rnn.forward(input_sequence)

    # Print the intermediate hidden states and final outputs
    for t, (h, y) in enumerate(zip(hidden_states, outputs)):
        print(f"Time Step {t+1}:")
        print("Hidden State:")
        print(h)
        print("Output:")
        print(y)
        print("---------")



Time Step 1:
Hidden State:
[[0.52893224]
 [0.55781144]]
Output:
[[0.70841946]
 [0.29158054]]
---------
Time Step 2:
Hidden State:
[[0.43065025]
 [0.30289697]]
Output:
[[0.65829093]
 [0.34170907]]
---------
Time Step 3:
Hidden State:
[[0.48084565]
 [0.35695703]]
Output:
[[0.67708987]
 [0.32291013]]
---------
